### ISSUE TITLE
Game keeps crashing

### ISSUE THREAD

**Issue by FalejevV** [SattesKrokodil/Fabric-Adventure-Pack#26]
This is the third world in a row that no longer starts. My game crashes with an error "java.lang.NullPointerException: Exception ticking world"

**To Reproduce**
Each time in a different way. The first time I just ran and the world broke. Now I was picking up loot from mobs and when I opened the inventory the world died.

**Desktop**
 - Launcher CurseForge
 - Version 4,3,3
 - Windows 10
 
---- Minecraft Crash Report ----
```
Time: 5/19/21 12:49 PM
Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at net.minecraft.class_1799.handler$ckm000$method17869Tail(class_1799.java:6185)
	at net.minecraft.class_1799.method_17869(class_1799.java:791)
	at net.minecraft.class_1799$$Lambda$7329/1688332956.accept(Unknown Source)
	at java.util.Optional.ifPresent(Optional.java:159)
	at net.minecraft.class_1799.method_17870(class_1799.java:791)
	at net.minecraft.class_1799.method_7950(class_1799.java:636)
	at mc.lootbeams.LootbeamsClient.lambda$null$1(LootbeamsClient.java:33)
	at mc.lootbeams.LootbeamsClient$$Lambda$10662/2059284435.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at mc.lootbeams.LootbeamsClient.lambda$onInitializeClient$4(LootbeamsClient.java:31)
	at mc.lootbeams.LootbeamsClient$$Lambda$5840/891454499.onEndTick(Unknown Source)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$6(ServerTickEvents.java:108)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents$$Lambda$2786/854329364.onEndTick(Unknown Source)
	at net.minecraft.class_1937.handler$dej000$tickWorldAfterBlockEntities(class_1937.java:4275)
	at net.minecraft.class_1937.method_18471(class_1937.java:557)
	at net.minecraft.class_3218.method_18765(class_3218.java:429)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.class_1132.method_3748(class_1132.java:91)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at net.minecraft.server.MinecraftServer$$Lambda$9934/374910002.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_1799.handler$ckm000$method17869Tail(class_1799.java:6185)
	at net.minecraft.class_1799.method_17869(class_1799.java:791)
	at net.minecraft.class_1799$$Lambda$7329/1688332956.accept(Unknown Source)
	at java.util.Optional.ifPresent(Optional.java:159)
	at net.minecraft.class_1799.method_17870(class_1799.java:791)
	at net.minecraft.class_1799.method_7950(class_1799.java:636)
	at mc.lootbeams.LootbeamsClient.lambda$null$1(LootbeamsClient.java:33)
	at mc.lootbeams.LootbeamsClient$$Lambda$10662/2059284435.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at mc.lootbeams.LootbeamsClient.lambda$onInitializeClient$4(LootbeamsClient.java:31)
	at mc.lootbeams.LootbeamsClient$$Lambda$5840/891454499.onEndTick(Unknown Source)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$6(ServerTickEvents.java:108)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents$$Lambda$2786/854329364.onEndTick(Unknown Source)
	at net.minecraft.class_1937.handler$dej000$tickWorldAfterBlockEntities(class_1937.java:4275)
	at net.minecraft.class_1937.method_18471(class_1937.java:557)
	at net.minecraft.class_3218.method_18765(class_3218.java:429)

-- Affected level --
Details:
	All players: 1 total; [class_3222['EasY000'/73, l='ServerLevel[NO CRASH Adventure...]', x=-193.63, y=134.00, z=-1835.92]]
	Chunk stats: ServerChunkCache: 3546
	Level dimension: minecraft:overworld
	Level spawn location: World: (-176,67,-112), Chunk: (at 0,4,0 in -11,-7; contains blocks -176,0,-112 to -161,255,-97), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 160213 game time, 221354 day time
	Level name: NO CRASH Adventure...
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 15620 (now: false), thunder time: 13140 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.class_1132.method_3748(class_1132.java:91)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at net.minecraft.server.MinecraftServer$$Lambda$9934/374910002.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2023118232 bytes (1929 MB) / 4740612096 bytes (4521 MB) up to 7277641728 bytes (6940 MB)
	CPUs: 8
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx7808m -Xms256m -XX:PermSize=256m
	Fabric Mods: 
		adorn: Adorn 1.13.0+1.16.5
		advancedchat: AdvancedChat 2.1.1
		advancements-enlarger: Advancements Enlarger 0.2.3
		adventurez: AdventureZ 1.2.2
		amecsapi: Amecs API 1.1.3+mc1.16.5
		angerable-patch: Angerable Patch 1.1.0-1.16.4
		anvil_fix: AnvilFix 1.2.1-1.16
		appleskin: AppleSkin 1.0.11
		architectury: Architectury 1.10.138
		artifice: Artifice 0.14.6+1.16.5
		autoconfig1u: Auto Config v1 Updated 3.3.1
		automated_crafting: Automated Crafting 1.3.20+MC1.16.2-1.16.5
		backslot: BackSlot 1.1.9
		balance_of_exile: Balance of Exile 1.0.3
		battletowers: Battle Towers 3.3.3-1.16.4
		bebooks: Better Enchanted Books 1.2.4
		beebetter: Bee Better 1.8.0-1.16.4
		beenfo: Beenfo 1.16.5-fabric0.30.0-1.3
		bettercaves: YUNG's Better Caves 1.16.5-1.1
		betterdroppeditems: Better Dropped Items 1.2.2-1.16.2
		betterend: Better End 0.9.1-pre
		bettermineshafts: YUNG's Better Mineshafts 1.16.4-1.0
		betternether: Better Nether 5.0.7
		biome_locator: Biome Locator 1.0.0
		biomemakeover: Biome Makeover 1.16.4-1.2.11
		blockus: Blockus 2.0.2+1.16.4
		blue_endless_jankson: jankson 1.2.0
		blur: Blur (Fabric) 2.0.0
		bowinfinityfix: Bow Infinity Fix rv9
		byg: BYG 1.1.5
		caelus: Caelus API 0.0.15-1.16.4
		cardinal-components: Cardinal Components API 2.7.13
		cardinal-components-base: Cardinal Components API (base) 2.7.13
		cardinal-components-block: Cardinal Components API (blocks) 2.7.13
		cardinal-components-chunk: Cardinal Components API (chunks) 2.7.13
		cardinal-components-entity: Cardinal Components API (entities) 2.7.13
		cardinal-components-item: Cardinal Components API (items) 2.7.13
		cardinal-components-level: Cardinal Components API (world saves) 2.7.13
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 2.7.13
		cardinal-components-util: Cardinal Components API (utilities) 2.7.13
		cardinal-components-world: Cardinal Components API (worlds) 2.7.13
		cavebiomes: Cave Biomes 0.6.2
		chainmail: Chainmail 0.5.0
		chains: Chains-Link 1.16.2-2.0.1
		charm: Charm 2.2.2
		chunkpregen: Fabric Chunk Pregenerator 0.3.3
		cinderscapes: Cinderscapes 1.3.3
		cleancut: CleanCut mc1.16-2.1-fabric
		cleanview: CleanView 1.16.5-v1-fabric
		cloth-api: Cloth API 1.4.9
		cloth-armor-api-v1: Cloth Armor API v1 1.4.9
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.5.47
		cloth-common-events-v1: Cloth Common Events v1 1.4.9
		cloth-config2: Cloth Config v4 4.11.14
		cloth-datagen-api-v1: Cloth Datagen v1 1.4.9
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.4.9
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.4.9
		cloth-scissors-api-v1: Cloth Scissors API v1 1.4.9
		cloth-utils-v1: Cloth Utils v1 1.4.9
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_github_therandomlabs_trlutils-config: TRLUtils-Config master-SNAPSHOT
		com_github_therandomlabs_trlutils-fabric: TRLUtils-Fabric 1.16-SNAPSHOT
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		compactstatuseffects: Compact Status Effects 1.2.2
		compressedblocks: Compressed Blocks 1.0
		controlling: Controlling For Fabric 1.1.2
		cosmetic-armor: Cosmetic Armor 1.0.0
		cotton-config: Cotton Config 1.0.0-rc.7
		cotton-logging: Cotton Logging 1.0.0-rc.4
		craftablehorsearmour: Craftable Horse Armour & Saddle 1.16-1.3-Fabric
		craftpresence: CraftPresence 1.7.6
		crawl: Crawl 0.8.1
		creeperspores: Creeper Spores 1.4.1
		crowdin-translate: CrowdinTranslate 1.2
		curios: Curios API 0.0.11-1.16.4
		curiouselytra: Curious Elytra 1.1.1-1.16.5
		curiousshulkerboxes: Curious Shulker Boxes 1.1.1-1.16.5
		customportalapi: customportalapi 0.0.1-beta23-1.16
		dark-loading-screen: Dark Loading Screen 1.5.0
		darkness: True Darkness 1.6.58
		deaths_wish: Death's Wish 1.3.6
		desolation: Desolation 1.1.0
		disablecustomworldsadvice: Disable Custom Worlds Advice 1.1
		dragonloot: DragonLoot 1.0.4
		dungeons_of_exile: Dungeons of Exile 1.1.1
		dynocaps: DynoCaps 1.6.16
		editsign: Edit Sign 2.2.0
		eldritch_mobs: Eldritch Mobs 1.6.8
		enchant_giver: Enchant Giver 1.0.3
		expandedstorage: ExpandedStorage 5.6.32
		extraalchemy: Extra Alchemy 1.3.1
		extradoors: ExtraDoors 1.8.2-1.16.2
		fabric: Fabric API 0.30.0+1.16
		fabric-api-base: Fabric API Base 0.2.0+ab87788d3a
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.0.10+ca58154a7d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.10+ca58154a7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.2+ca58154a7d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-furnaces: Fabric Furnaces 1.3.3-1.16.4
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.3+ca58154a7d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.2+ca58154a7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-language-kotlin: Fabric Language Kotlin 1.4.21+build.1
		fabric-language-scala: Fabric Language Scala 1.0.0
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.2.1+ca58154a7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.3+ca58154a7d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.1+ca58154a7d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.1+ca58154a7d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.5.1+ca58154a7d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.2+ca58154a7d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.1+ca58154a7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.6+ca58154a7d
		fabricloader: Fabric Loader 0.11.1
		fallflyinglib: FallFlyingLib 1.1.0
		fallingtree: FallingTree 2.10.2
		fatxporbs: Fat Experience Orbs 0.0.9
		fiber: fiber 0.23.0-2
		fiber2cloth: Fiber To Cloth 3.0.1
		flan: Flan 1.16.2-1.2.3
		ftbguilibrary: FTB GUI Library 1605.2.1.40
		ftbquests: FTB Quests 1605.2.1-build.39
		gbfabrictools: GBfabrictools 1.3.2+1.16.4
		geckolib3: Geckolib 3.0.22
		globalspawn: GlobalSpawn 1.1.2-1.16.5
		go-fish: Go Fish 1.2.1-beta-1.16.4
		goldensteak: Goldensteak 1.0.2
		grindenchantments: Grind Enchantments 1.1.3+1.16.3
		harvest: Harvest 1.2.12
		headshot: Headshot 1.0.6
		heartbond: Heartbond 1.0.0
		homecamp: Home Camp 1.0.3
		iamverysmart: I Am Very Smart 2.1.0+mc1.16.1
		identity: Identity 1.11.8-beta-1.16.5
		inventoryhud: Inventory HUD + 3.2.2
		invtrashslot: InvTrashSlot 1.0.2
		io_github_onyxstudios_cardinal-components-api: Cardinal-Components-API 2.7.9
		itemfilters: Item Filters 1605.2.4-build.30
		itemflexer: ItemFlexer 1.1.4
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 8
		jumploader: Jumploader 2.1.3
		kirin: Kirin UI 1.7-1.16.2
		kubejs: KubeJS 1605.3.6-build.177
		kyrptconfig: Kytpt Config 1.1.6-1.16
		lambdynlights: LambDynamicLights 1.3.4+1.16
		libblockattributes: LibBlockAttributes 0.8.5
		libblockattributes_core: LibBlockAttributes (Core) 0.8.5
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.5
		libblockattributes_items: LibBlockAttributes (Items) 0.8.5
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.3.2+1.16.4
		library_of_exile: Library of Exile 1.0.6
		libstructure: LibStructure 1.5
		limitedspawners: Limited Spawner 1.0.1
		lootbeams: Lootbeams 2.0.0
		lootcrates: LootCrates 1.0.0
		mambience: MAmbience 3.0.0+1.16.5
		mcda: MC Dungeons Armors 1.3.7
		mcdw: MC Dungeons Weapons 3.0.6
		mesh: Mesh 0.6.1-alpha.21+1.16.4
		mesh_api: Mesh API 0.6.1-alpha.21+1.16.4
		microconfig: Microconfig 1.1.0
		minecraft: Minecraft 1.16.5
		mm: Manningham Mills 2.1
		mmorpg: Age of Exile 1.7.13
		mobz: MobZ 2.4.5
		modmenu: Mod Menu 1.16.8
		mostructures: Mo' Structures 1.1.0+mc.1.16.5
		mousewheelie: Mouse Wheelie 1.6.4+mc1.16.4
		nbtcrafting: NBT Crafting 2.0.5+mc1.16.4
		nomoreglowingpots: No More Glowing Pots 1.0.2
		org_aeonbits_owner_owner: owner 1.0.12
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_codehaus_groovy_groovy: groovy 3.0.3
		org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.3
		org_jetbrains_annotations: annotations 20.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.21
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.4.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.4.2
		org_yaml_snakeyaml: snakeyaml 1.25
		origins: Origins 0.4.7
		origins-classes: Origins: Classes 1.1.1
		overworld_two: Overworld 2 1.0.4
		patchouli: Patchouli 1.16.4-48-FABRIC
		petowner: Pet Owner 1.7.1-1.16.2+
		phosphor: Phosphor 0.7.1+build.11
		plantinajar: Plant In A Jar 1.8.1
		playerabilitylib: Pal 1.2.1
		pling: Pling 1.2.0
		polymorph: Polymorph 0.0.9-1.16.5
		presencefootsteps: Presence Footsteps r29+1.16.4
		programmerartinjector: Programmer Art Injector 1.2.1
		quickshulker: Quick Shulker 1.1.14-1.16
		randompatches: RandomPatches 1.16.1-0.0.0.5-fabric
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		reauth: ReAuth 3.9.3
		repurposed_structures: Repurposed Structures 1.16.5-1.8.7
		rhino: Rhino 1.7.13-build.14
		roughlyenoughitems: Roughly Enough Items 5.10.181
		roughlyenoughitems-api: REI (API) 5.10.181
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.10.181
		roughlyenoughitems-runtime: REI (Runtime) 5.10.181
		roughlyenoughresources: Roughly Enough Resources 2.1.3
		satin: Satin 1.5.1
		secretrooms: Secret Rooms 0.9.3+1.16.5
		sgod: Save Gear on Death 0.0.2
		shulkerboxtooltip: Shulker Box Tooltip 2.3.5+1.16.5
		shulkerutils: shulkerutils 1.0.1-1.16
		simpleteleporters: Simple Teleporters 2.2.1
		simplevoidworld: Simple Void World 4.0.0
		slight-gui-modifications: 'Slight' GUI Modifications 1.7.1
		sodium: Sodium 0.1.0
		someforgepatchesported: Some Forge Patches Ported 1.0.0
		spruceui: SpruceUI 2.0.4+1.16
		starry_sky: Starry Skies 1.0.9-1.16.5
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		structure-helpers: Structure Helpers 3.0.0
		taterzens: Taterzens 0.2.0-1.16.5
		terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 1.0.4
		terraform-config-api-v1: Terraform Config API (v1) 1.0.3
		terraform-dirt-api-v1: Terraform Dirt API (v1) 1.1.3
		terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 1.0.3
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.3
		terraform-surfaces-api-v1: Terraform Surfaces API (v1) 1.0.3
		terraform-tree-api-v1: Terraform Tree API (v1) 1.0.4
		terraform-wood-api-v1: Terraform Wood API (v1) 1.0.3
		terrestria: Terrestria 2.2.0
		tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.2
		toms_storage: Tom's Simple Storage Mod 1.1.9
		transferchestmod: Transfer Chest 1.1.4
		trapexpansion: Trap Expansion 1.3.2
		traverse: Traverse 3.3.2
		tweed: Tweed API 3.0.0-beta.22
		voyager: Voyager 1.0.0
		walljump: Wall-Jump! 1.3.3+1.16.1
		winged: Winged Mod 1.16.2-1.4.1
		wolveswitharmor: Wolves With Armor 1.5.2-1.16.2
		worldedit: WorldEdit 7.2.4+5723-e3bfc64
		wthit: wthit 2.2.1+1.16.5
		xaerominimap: Xaero's Minimap 21.3.0
		xaeroworldmap: Xaero's World Map 1.12.0
		xp_storage: XP Storage 1.4+1.16.5
		yungsapi: YUNG's API 1.16.5-Fabric-2
		zoob: Monster Of The Ocean Depths 3.0.0
	Patchouli open book context: n/a
	Player Count: 1 / 8; [class_3222['EasY000'/73, l='ServerLevel[NO CRASH Adventure...]', x=-193.63, y=134.00, z=-1835.92]]
	Data Packs: vanilla, deaths_wish:deaths_wish_datapack, null, Fabric Mods
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'
```

**Comment by FalejevV** [comment]
I'm not sure if this is a 100% solution, (so far) the game does not crash.
I removed the lootbeams plugin and increased the RAM.
